name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Pest on PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: ['7.4', '8.0']
    env:
      extensions: bcmath

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Test php code
        run: composer pest:test
